-- Ex 8
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
USE hbtn_0d_usa;

CREATE TABLE IF NOT EXISTS cities(
  id INT AUTO_INCREMENT PRIMARY KEY,
  state_id INT NOT NULL,
  FOREING KEY (state_id) REFERENCES (id)
  name VARCHAR(256) NOT NULL
);
